# Generated by Django 4.0.1 on 2022-02-06 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_posts', '0002_blogpostmodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUserModel',
        ),
    ]
