# Generated by Django 4.0.1 on 2022-02-06 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_posts', '0004_customusermodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUserModel',
        ),
    ]
