# Generated by Django 4.0.1 on 2022-02-07 12:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog_posts', '0005_delete_customusermodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpostmodel',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Author'),
        ),
        migrations.AlterField(
            model_name='blogpostmodel',
            name='published_at',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Published Date'),
        ),
    ]
